### ISSUE TITLE
Not able to pick image from the gallery

### ISSUE THREAD

**Issue by Shajeel-Afzal** [stfalcon-studio/ContentManager#1]
The library is not working, I tried picking up the image from the Gallery in Samsung S7 Edge but onActivityResult is never called.

I am testing it inside the Fragment on Android OS version 6.0

**Comment by bevzaanton** [comment]
Hi! Please update the library version to 0.2:
`compile 'com.github.stfalcon:contentmanager:0.2'`

And don't forget override onRequestPermissionsResult method in your activity(fragment) to handle realtime permissions.

```
@Override
public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
    super.onRequestPermissionsResult(requestCode, permissions, grantResults);
    contentManager.onRequestPermissionsResult(requestCode, permissions, grantResults);
}
```

Please let me know if anything wrong
