### ISSUE TITLE
Previewing captured image?

### ISSUE THREAD

**Issue by dotocan** [stfalcon-studio/ContentManager#2]
Hi,

Picking image from gallery and putting it in ImageView works as it should. But how can I take a picture with camera and put that captured image into ImageView? I need to be able to take a picture with camera on one activity and then show that picture to the user few activities later.

**Comment by bevzaanton** [comment]
If you want to take a picture with camera you have to use:
`contentManager.takePhoto();` 
instead of
`contentManager.pickContent(ContentManager.Content.IMAGE);`

**Comment by dotocan** [comment]
Sorry, I didn't construct my sentence clear enough. I know that I have to use takePhoto method. What I didn't know was how to get the image I just captured so I can load that image into ImageView. In other words, I didn't know that I have to use onActivityResult's data.getData() method to get the captured image. Thanks anyway :) Closing the issue
