### ISSUE TITLE
onActivityResult data is null

### ISSUE THREAD

**Issue by dotocan** [stfalcon-studio/ContentManager#3]
Hi, 
when using contentmanager.takephoto() on some devices the app crashes. I can see this error in logs:

_Exception java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=16, result=-1, data=null} to activity {...activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference_ 

It seems that on those devices, intent data received in onActivityResult is null. 

Devices on which I tested it and it works perfectly:
- Samsung Galaxy S5 mini with android 5.1.1
- LG Nexus 5 with android 6.0.1

Devices on which I see this error:
- Motorola Moto G with android 5.1
- Huawei honor 6 with android 4.4.2
- Android Studio official emulator

**Comment by dotocan** [comment]
@stfalcon sorry to bother, but can I expect this to be resolved by the end of this or at least next week? Those two phones on which it doesn't work are my client's and he wants to be able to use his app as soon as possible.

**Comment by bevzaanton** [comment]
Hi, sorry for a delay. I have tested taking from a camera on Android Studio official emulator and Motorola Moto G, and all was fine. 
Can you post your overridden method onActivityResult?

**Comment by dotocan** [comment]
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {

```
    if (resultCode == RESULT_OK) {
        contentManager.onActivityResult(requestCode, resultCode, data);
        Glide.with(this).load(data.getData()).into(imgFromCamera);

        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putString(KEY_FILE_URI, String.valueOf(data.getData()));
        editor.commit();
    } else {
        Toast.makeText(this, "Image capture failed!", Toast.LENGTH_SHORT).show();
    }

}
```

**Comment by dotocan** [comment]
It breaks on a Glide line, but it's not because ov the Glide itself, it breaks when I try to log it or do anything with it. The part which breaks it is "data.getData()"

**Comment by bevzaanton** [comment]
You have to paste Glide code in onContentLoaded

```
@Override
public void onContentLoaded(Uri uri, String contentType) {
      Glide.with(this).load(uri).into(imgFromCamera);

      SharedPreferences.Editor editor = sharedPreferences.edit();
      editor.putString(KEY_FILE_URI,  uri.toString());
      editor.commit();
} 
```

And in onActivityResult just:

```
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
  super.onActivityResult(requestCode, resultCode, data);
  contentManager.onActivityResult(requestCode, resultCode, data);
}
```

And please update version ContentManager in your gradle file to 0.3:

```
compile 'com.github.stfalcon:contentmanager:0.3'
```

**Comment by dotocan** [comment]
Ok, thank you, it works now.
