### ISSUE TITLE
onContentLoaded not called when don't keep activities is set and picking from gallery

### ISSUE THREAD

**Issue by danielto** [stfalcon-studio/ContentManager#4]
Hello,

thank you for your library. I found out that when I turn on the "don't keep activities" option the onContentLoaded is not called when picking an image from gallery. It works fine when taking a picture from cammera. Also when I don't have this option turned on it works for camera and gallery. 

I was using 0.1.1 version but after upgrade to 0.4.2 it is still the same. Do you have any idea where can by the problem?   

Fragments onActivityResult is called and it contains this code:

`@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        contentManager.onActivityResult(requestCode, resultCode, data);
    }`

Thank you for you response.

**Comment by bevzaanton** [comment]
Hi, @danndi !
Thank you for your interest in my library.
Yes, you are right, it was a bug. I have already fixed it.
Please update your gradle dependency to `compile 'com.github.stfalcon:contentmanager:0.4.3'`
And don't forget these methods in your activity. It's necessary:
```
@Override
    protected void onRestoreInstanceState(Bundle savedInstanceState) {
        super.onRestoreInstanceState(savedInstanceState);
        contentManager.onRestoreInstanceState(savedInstanceState);
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        contentManager.onSaveInstanceState(outState);
    }
```
Please, let me know if I solve your problem.

**Comment by danielto** [comment]
Hi @bevzaanton !

Thank you very much for such a quick response and fix. It is working like a charm after the upgrade :). Good job!
