### ISSUE TITLE
onLoadContentProgress(int loadPercent) called even for local images

### ISSUE THREAD

**Issue by 16arm** [stfalcon-studio/ContentManager#6]
Hello, 

First, I want to thank you for your library.
I'm asking a question about the onLoadContentProgress() call.
I logged some information in this callback method and I can see that calls are done even for local images. I think this method should be called only for cloud images.

Thanks, 16arm

**Comment by bevzaanton** [comment]
Hi, @16arm ! Thank you, for your interest in my library.
I have updated the library to version 0.5. Take a look [Migration to version 0.5](https://github.com/stfalcon-studio/ContentManager/blob/master/README.md#migration-to-version-05) in README.
